package com.sentinel.api.model;

public enum AuditAction {
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_DELETED,
    API_KEY_CREATED,
    API_KEY_UPDATED,
    API_KEY_REVOKED,
    API_KEY_REGENERATED,
    API_KEY_DELETED,
    POLICY_CREATED,
    POLICY_UPDATED,
    POLICY_DELETED,
    ALERT_RULE_CREATED,
    ALERT_RULE_UPDATED,
    ALERT_RULE_DELETED,
    ALERT_ACKNOWLEDGED,
    ALERT_RESOLVED,
    UPSTREAM_AUTH_CONFIGURED,
    UPSTREAM_AUTH_UPDATED,
    UPSTREAM_AUTH_DISABLED,
    UPSTREAM_CONNECTION_TESTED
}
