spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: ${PORT:8080}
logging:
  level:
    root: WARN
    com.sentinel.api: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
